//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvGestionComercial
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionComercial.SolicitudSoap")]
    public interface SolicitudSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleSolicitud", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Threading.Tasks.Task<srvGestionComercial.DetalleSolicitudResponseDetalleSolicitudResult> DetalleSolicitudAsync(string V_CEO, string V_ID_SOLICITUD, string V_COD_DIV, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarSolicitudTrabajo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Threading.Tasks.Task<srvGestionComercial.ListarSolicitudTrabajoResponseListarSolicitudTrabajoResult> ListarSolicitudTrabajoAsync(string V_AMBIENTE, string V_FILTRO, string V_CEO, string V_UND_OPER, string V_FEC_STR_INI, string V_FEC_STR_FIN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarSolicitudTrabajo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Threading.Tasks.Task<string> ListarSolicitudTrabajo2Async(string V_AMBIENTE, string V_FILTRO, string V_CEO, string V_UND_OPER, string V_FEC_STR_INI, string V_FEC_STR_FIN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarSolicitud", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Threading.Tasks.Task<string> InsertarSolicitudAsync(
                    string v_ambiente, 
                    string v_cod_ceo, 
                    string v_cod_div, 
                    string v_nro_str, 
                    string v_cod_aus, 
                    string v_tip_str, 
                    string v_cod_cli, 
                    string v_cod_und, 
                    string v_cod_sis, 
                    string v_cod_sub, 
                    string v_cod_eqp, 
                    string v_fec_str, 
                    string v_nro_val, 
                    string v_tip_tbj, 
                    string v_cod_pro, 
                    string v_est_atl, 
                    string v_des_abr, 
                    string v_des_det, 
                    string v_nro_pro, 
                    string v_ref_str, 
                    string v_ubc_eqp, 
                    string v_tip_tar, 
                    string v_cls_tbj, 
                    string v_cod_nav, 
                    string v_fec_ref, 
                    string v_fec_acc, 
                    string v_alias_str, 
                    string v_ind_cnv, 
                    string v_fec_cnv, 
                    string v_ibp, 
                    string v_tip_ots, 
                    string v_usr_reg, 
                    string v_fec_reg, 
                    string v_ots_tar, 
                    string v_fec_rcp_str, 
                    string v_hra_rcp_str, 
                    string v_fec_ent_val, 
                    string v_hra_ent_val, 
                    string v_dique, 
                    string v_cod_sec, 
                    string v_tipo_val, 
                    string v_nro_ctto, 
                    string v_nro_sol_jde, 
                    string v_est_prc, 
                    string v_ref_str_mgp, 
                    string v_fec_ref_mgp, 
                    string v_cod_cliente, 
                    string v_proyecto, 
                    string v_sublinea, 
                    string v_otgenerica, 
                    string v_numacti, 
                    string v_actividad, 
                    string v_estructura, 
                    string v_estacionregistro, 
                    string v_v_solicitud_id, 
                    string v_v_embarcacion_id, 
                    string v_v_cliente_id, 
                    string v_und_ope, 
                    string v_nro_revision, 
                    string v_cod_presupuesto, 
                    string v_remitido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarSolicitud2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Threading.Tasks.Task<string> InsertarSolicitud2Async(srvGestionComercial.SolicitudBE oSolicitudBE, string UserName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class DetalleSolicitudResponseDetalleSolicitudResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SolicitudBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBE
    {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado
        {
            get
            {
                return this.idEstadoField;
            }
            set
            {
                this.idEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado
        {
            get
            {
                return this.imgEstadoField;
            }
            set
            {
                this.imgEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado
        {
            get
            {
                return this.nombreEstadoField;
            }
            set
            {
                this.nombreEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IdCodigo
        {
            get
            {
                return this.idCodigoField;
            }
            set
            {
                this.idCodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IdUsuario
        {
            get
            {
                return this.idUsuarioField;
            }
            set
            {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ambiente
        {
            get
            {
                return this.ambienteField;
            }
            set
            {
                this.ambienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SolicitudBE : BaseBE
    {
        
        private string v_AMBIENTEField;
        
        private string x_COD_CEOField;
        
        private string x_COD_DIVField;
        
        private int x_NRO_STRField;
        
        private string x_COD_AUSField;
        
        private string x_TIP_STRField;
        
        private int x_COD_CLIField;
        
        private int x_COD_UNDField;
        
        private int x_COD_SISField;
        
        private int x_COD_SUBField;
        
        private int x_COD_EQPField;
        
        private string x_FEC_STRField;
        
        private int x_NRO_VALField;
        
        private string x_TIP_TBJField;
        
        private int x_COD_PROField;
        
        private string x_EST_ATLField;
        
        private string x_DES_ABRField;
        
        private string x_DES_DETField;
        
        private int x_NRO_PROField;
        
        private string x_REF_STRField;
        
        private string x_UBC_EQPField;
        
        private string x_TIP_TARField;
        
        private string x_CLS_TBJField;
        
        private int x_COD_NAVField;
        
        private string x_FEC_REFField;
        
        private string x_FEC_ACCField;
        
        private string x_ALIAS_STRField;
        
        private string x_IND_CNVField;
        
        private string x_FEC_CNVField;
        
        private string x_IBPField;
        
        private string x_TIP_OTSField;
        
        private string x_USR_REGField;
        
        private string x_FEC_REGField;
        
        private string x_OTS_TARField;
        
        private string x_FEC_RCP_STRField;
        
        private string x_HRA_RCP_STRField;
        
        private string x_FEC_ENT_VALField;
        
        private string x_HRA_ENT_VALField;
        
        private string x_DIQUEField;
        
        private string x_COD_SECField;
        
        private string x_TIPO_VALField;
        
        private string x_NRO_CTTOField;
        
        private int x_NRO_SOL_JDEField;
        
        private int x_EST_PRCField;
        
        private string x_REF_STR_MGPField;
        
        private string x_FEC_REF_MGPField;
        
        private string x_COD_CLIENTEField;
        
        private string x_PROYECTOField;
        
        private string x_SUBLINEAField;
        
        private string x_OTGENERICAField;
        
        private string x_NUMACTIField;
        
        private string x_ACTIVIDADField;
        
        private string x_ESTRUCTURAField;
        
        private string x_ESTACIONREGISTROField;
        
        private string x_V_SOLICITUD_IDField;
        
        private string x_V_EMBARCACION_IDField;
        
        private string x_V_CLIENTE_IDField;
        
        private string x_UND_OPEField;
        
        private string x_NRO_REVISIONField;
        
        private string x_COD_PRESUPUESTOField;
        
        private string x_REMITIDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string V_AMBIENTE
        {
            get
            {
                return this.v_AMBIENTEField;
            }
            set
            {
                this.v_AMBIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string X_COD_CEO
        {
            get
            {
                return this.x_COD_CEOField;
            }
            set
            {
                this.x_COD_CEOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string X_COD_DIV
        {
            get
            {
                return this.x_COD_DIVField;
            }
            set
            {
                this.x_COD_DIVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int X_NRO_STR
        {
            get
            {
                return this.x_NRO_STRField;
            }
            set
            {
                this.x_NRO_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string X_COD_AUS
        {
            get
            {
                return this.x_COD_AUSField;
            }
            set
            {
                this.x_COD_AUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string X_TIP_STR
        {
            get
            {
                return this.x_TIP_STRField;
            }
            set
            {
                this.x_TIP_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int X_COD_CLI
        {
            get
            {
                return this.x_COD_CLIField;
            }
            set
            {
                this.x_COD_CLIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int X_COD_UND
        {
            get
            {
                return this.x_COD_UNDField;
            }
            set
            {
                this.x_COD_UNDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int X_COD_SIS
        {
            get
            {
                return this.x_COD_SISField;
            }
            set
            {
                this.x_COD_SISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int X_COD_SUB
        {
            get
            {
                return this.x_COD_SUBField;
            }
            set
            {
                this.x_COD_SUBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int X_COD_EQP
        {
            get
            {
                return this.x_COD_EQPField;
            }
            set
            {
                this.x_COD_EQPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string X_FEC_STR
        {
            get
            {
                return this.x_FEC_STRField;
            }
            set
            {
                this.x_FEC_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int X_NRO_VAL
        {
            get
            {
                return this.x_NRO_VALField;
            }
            set
            {
                this.x_NRO_VALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string X_TIP_TBJ
        {
            get
            {
                return this.x_TIP_TBJField;
            }
            set
            {
                this.x_TIP_TBJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int X_COD_PRO
        {
            get
            {
                return this.x_COD_PROField;
            }
            set
            {
                this.x_COD_PROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string X_EST_ATL
        {
            get
            {
                return this.x_EST_ATLField;
            }
            set
            {
                this.x_EST_ATLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string X_DES_ABR
        {
            get
            {
                return this.x_DES_ABRField;
            }
            set
            {
                this.x_DES_ABRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string X_DES_DET
        {
            get
            {
                return this.x_DES_DETField;
            }
            set
            {
                this.x_DES_DETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int X_NRO_PRO
        {
            get
            {
                return this.x_NRO_PROField;
            }
            set
            {
                this.x_NRO_PROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string X_REF_STR
        {
            get
            {
                return this.x_REF_STRField;
            }
            set
            {
                this.x_REF_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string X_UBC_EQP
        {
            get
            {
                return this.x_UBC_EQPField;
            }
            set
            {
                this.x_UBC_EQPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string X_TIP_TAR
        {
            get
            {
                return this.x_TIP_TARField;
            }
            set
            {
                this.x_TIP_TARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string X_CLS_TBJ
        {
            get
            {
                return this.x_CLS_TBJField;
            }
            set
            {
                this.x_CLS_TBJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int X_COD_NAV
        {
            get
            {
                return this.x_COD_NAVField;
            }
            set
            {
                this.x_COD_NAVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string X_FEC_REF
        {
            get
            {
                return this.x_FEC_REFField;
            }
            set
            {
                this.x_FEC_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string X_FEC_ACC
        {
            get
            {
                return this.x_FEC_ACCField;
            }
            set
            {
                this.x_FEC_ACCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string X_ALIAS_STR
        {
            get
            {
                return this.x_ALIAS_STRField;
            }
            set
            {
                this.x_ALIAS_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string X_IND_CNV
        {
            get
            {
                return this.x_IND_CNVField;
            }
            set
            {
                this.x_IND_CNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string X_FEC_CNV
        {
            get
            {
                return this.x_FEC_CNVField;
            }
            set
            {
                this.x_FEC_CNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string X_IBP
        {
            get
            {
                return this.x_IBPField;
            }
            set
            {
                this.x_IBPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string X_TIP_OTS
        {
            get
            {
                return this.x_TIP_OTSField;
            }
            set
            {
                this.x_TIP_OTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string X_USR_REG
        {
            get
            {
                return this.x_USR_REGField;
            }
            set
            {
                this.x_USR_REGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string X_FEC_REG
        {
            get
            {
                return this.x_FEC_REGField;
            }
            set
            {
                this.x_FEC_REGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string X_OTS_TAR
        {
            get
            {
                return this.x_OTS_TARField;
            }
            set
            {
                this.x_OTS_TARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string X_FEC_RCP_STR
        {
            get
            {
                return this.x_FEC_RCP_STRField;
            }
            set
            {
                this.x_FEC_RCP_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string X_HRA_RCP_STR
        {
            get
            {
                return this.x_HRA_RCP_STRField;
            }
            set
            {
                this.x_HRA_RCP_STRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string X_FEC_ENT_VAL
        {
            get
            {
                return this.x_FEC_ENT_VALField;
            }
            set
            {
                this.x_FEC_ENT_VALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string X_HRA_ENT_VAL
        {
            get
            {
                return this.x_HRA_ENT_VALField;
            }
            set
            {
                this.x_HRA_ENT_VALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string X_DIQUE
        {
            get
            {
                return this.x_DIQUEField;
            }
            set
            {
                this.x_DIQUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string X_COD_SEC
        {
            get
            {
                return this.x_COD_SECField;
            }
            set
            {
                this.x_COD_SECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string X_TIPO_VAL
        {
            get
            {
                return this.x_TIPO_VALField;
            }
            set
            {
                this.x_TIPO_VALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string X_NRO_CTTO
        {
            get
            {
                return this.x_NRO_CTTOField;
            }
            set
            {
                this.x_NRO_CTTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public int X_NRO_SOL_JDE
        {
            get
            {
                return this.x_NRO_SOL_JDEField;
            }
            set
            {
                this.x_NRO_SOL_JDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public int X_EST_PRC
        {
            get
            {
                return this.x_EST_PRCField;
            }
            set
            {
                this.x_EST_PRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string X_REF_STR_MGP
        {
            get
            {
                return this.x_REF_STR_MGPField;
            }
            set
            {
                this.x_REF_STR_MGPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string X_FEC_REF_MGP
        {
            get
            {
                return this.x_FEC_REF_MGPField;
            }
            set
            {
                this.x_FEC_REF_MGPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string X_COD_CLIENTE
        {
            get
            {
                return this.x_COD_CLIENTEField;
            }
            set
            {
                this.x_COD_CLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string X_PROYECTO
        {
            get
            {
                return this.x_PROYECTOField;
            }
            set
            {
                this.x_PROYECTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string X_SUBLINEA
        {
            get
            {
                return this.x_SUBLINEAField;
            }
            set
            {
                this.x_SUBLINEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string X_OTGENERICA
        {
            get
            {
                return this.x_OTGENERICAField;
            }
            set
            {
                this.x_OTGENERICAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string X_NUMACTI
        {
            get
            {
                return this.x_NUMACTIField;
            }
            set
            {
                this.x_NUMACTIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string X_ACTIVIDAD
        {
            get
            {
                return this.x_ACTIVIDADField;
            }
            set
            {
                this.x_ACTIVIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string X_ESTRUCTURA
        {
            get
            {
                return this.x_ESTRUCTURAField;
            }
            set
            {
                this.x_ESTRUCTURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string X_ESTACIONREGISTRO
        {
            get
            {
                return this.x_ESTACIONREGISTROField;
            }
            set
            {
                this.x_ESTACIONREGISTROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string X_V_SOLICITUD_ID
        {
            get
            {
                return this.x_V_SOLICITUD_IDField;
            }
            set
            {
                this.x_V_SOLICITUD_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string X_V_EMBARCACION_ID
        {
            get
            {
                return this.x_V_EMBARCACION_IDField;
            }
            set
            {
                this.x_V_EMBARCACION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string X_V_CLIENTE_ID
        {
            get
            {
                return this.x_V_CLIENTE_IDField;
            }
            set
            {
                this.x_V_CLIENTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string X_UND_OPE
        {
            get
            {
                return this.x_UND_OPEField;
            }
            set
            {
                this.x_UND_OPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string X_NRO_REVISION
        {
            get
            {
                return this.x_NRO_REVISIONField;
            }
            set
            {
                this.x_NRO_REVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string X_COD_PRESUPUESTO
        {
            get
            {
                return this.x_COD_PRESUPUESTOField;
            }
            set
            {
                this.x_COD_PRESUPUESTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string X_REMITIDO
        {
            get
            {
                return this.x_REMITIDOField;
            }
            set
            {
                this.x_REMITIDOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ListarSolicitudTrabajoResponseListarSolicitudTrabajoResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SolicitudSoapChannel : srvGestionComercial.SolicitudSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SolicitudSoapClient : System.ServiceModel.ClientBase<srvGestionComercial.SolicitudSoap>, srvGestionComercial.SolicitudSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SolicitudSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SolicitudSoapClient.GetBindingForEndpoint(endpointConfiguration), SolicitudSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SolicitudSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SolicitudSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<srvGestionComercial.DetalleSolicitudResponseDetalleSolicitudResult> DetalleSolicitudAsync(string V_CEO, string V_ID_SOLICITUD, string V_COD_DIV, string UserName)
        {
            return base.Channel.DetalleSolicitudAsync(V_CEO, V_ID_SOLICITUD, V_COD_DIV, UserName);
        }
        
        public System.Threading.Tasks.Task<srvGestionComercial.ListarSolicitudTrabajoResponseListarSolicitudTrabajoResult> ListarSolicitudTrabajoAsync(string V_AMBIENTE, string V_FILTRO, string V_CEO, string V_UND_OPER, string V_FEC_STR_INI, string V_FEC_STR_FIN, string UserName)
        {
            return base.Channel.ListarSolicitudTrabajoAsync(V_AMBIENTE, V_FILTRO, V_CEO, V_UND_OPER, V_FEC_STR_INI, V_FEC_STR_FIN, UserName);
        }
        
        public System.Threading.Tasks.Task<string> ListarSolicitudTrabajo2Async(string V_AMBIENTE, string V_FILTRO, string V_CEO, string V_UND_OPER, string V_FEC_STR_INI, string V_FEC_STR_FIN, string UserName)
        {
            return base.Channel.ListarSolicitudTrabajo2Async(V_AMBIENTE, V_FILTRO, V_CEO, V_UND_OPER, V_FEC_STR_INI, V_FEC_STR_FIN, UserName);
        }
        
        public System.Threading.Tasks.Task<string> InsertarSolicitudAsync(
                    string v_ambiente, 
                    string v_cod_ceo, 
                    string v_cod_div, 
                    string v_nro_str, 
                    string v_cod_aus, 
                    string v_tip_str, 
                    string v_cod_cli, 
                    string v_cod_und, 
                    string v_cod_sis, 
                    string v_cod_sub, 
                    string v_cod_eqp, 
                    string v_fec_str, 
                    string v_nro_val, 
                    string v_tip_tbj, 
                    string v_cod_pro, 
                    string v_est_atl, 
                    string v_des_abr, 
                    string v_des_det, 
                    string v_nro_pro, 
                    string v_ref_str, 
                    string v_ubc_eqp, 
                    string v_tip_tar, 
                    string v_cls_tbj, 
                    string v_cod_nav, 
                    string v_fec_ref, 
                    string v_fec_acc, 
                    string v_alias_str, 
                    string v_ind_cnv, 
                    string v_fec_cnv, 
                    string v_ibp, 
                    string v_tip_ots, 
                    string v_usr_reg, 
                    string v_fec_reg, 
                    string v_ots_tar, 
                    string v_fec_rcp_str, 
                    string v_hra_rcp_str, 
                    string v_fec_ent_val, 
                    string v_hra_ent_val, 
                    string v_dique, 
                    string v_cod_sec, 
                    string v_tipo_val, 
                    string v_nro_ctto, 
                    string v_nro_sol_jde, 
                    string v_est_prc, 
                    string v_ref_str_mgp, 
                    string v_fec_ref_mgp, 
                    string v_cod_cliente, 
                    string v_proyecto, 
                    string v_sublinea, 
                    string v_otgenerica, 
                    string v_numacti, 
                    string v_actividad, 
                    string v_estructura, 
                    string v_estacionregistro, 
                    string v_v_solicitud_id, 
                    string v_v_embarcacion_id, 
                    string v_v_cliente_id, 
                    string v_und_ope, 
                    string v_nro_revision, 
                    string v_cod_presupuesto, 
                    string v_remitido)
        {
            return base.Channel.InsertarSolicitudAsync(v_ambiente, v_cod_ceo, v_cod_div, v_nro_str, v_cod_aus, v_tip_str, v_cod_cli, v_cod_und, v_cod_sis, v_cod_sub, v_cod_eqp, v_fec_str, v_nro_val, v_tip_tbj, v_cod_pro, v_est_atl, v_des_abr, v_des_det, v_nro_pro, v_ref_str, v_ubc_eqp, v_tip_tar, v_cls_tbj, v_cod_nav, v_fec_ref, v_fec_acc, v_alias_str, v_ind_cnv, v_fec_cnv, v_ibp, v_tip_ots, v_usr_reg, v_fec_reg, v_ots_tar, v_fec_rcp_str, v_hra_rcp_str, v_fec_ent_val, v_hra_ent_val, v_dique, v_cod_sec, v_tipo_val, v_nro_ctto, v_nro_sol_jde, v_est_prc, v_ref_str_mgp, v_fec_ref_mgp, v_cod_cliente, v_proyecto, v_sublinea, v_otgenerica, v_numacti, v_actividad, v_estructura, v_estacionregistro, v_v_solicitud_id, v_v_embarcacion_id, v_v_cliente_id, v_und_ope, v_nro_revision, v_cod_presupuesto, v_remitido);
        }
        
        public System.Threading.Tasks.Task<string> InsertarSolicitud2Async(srvGestionComercial.SolicitudBE oSolicitudBE, string UserName)
        {
            return base.Channel.InsertarSolicitud2Async(oSolicitudBE, UserName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SolicitudSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SolicitudSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SolicitudSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.90.4:7000/Core/GestionComercial/Solicitud.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SolicitudSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.90.4:7000/Core/GestionComercial/Solicitud.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SolicitudSoap,
            
            SolicitudSoap12,
        }
    }
}
